change server.js
net-art-and-cultures/data-bodies pull request #40
Opened 2019-12-05 07:22 UTC by jlee273

I used the format of app.post(/api/image-uploaded)
app.get(/api/images). I'm not sure what should I add.

2019-12-05 15:43 UTC, nbriz commented
@jlee273 did u watch the video i sent to the class via email? i explain more or less what u should do in that video. for `app.post('/api/image-upload')` u should use the 'multer' library (explained in the video i made) && for `app.get('/api/images')` u should use the `fs` module to read all the filenames in the folder && send them back as json. in the video i explain how to send json back, but i don't explain how to read all the file names in a folder, but [this post ](https://stackoverflow.com/questions/2727167/how-do-you-get-a-list-of-the-names-of-all-files-present-in-a-directory-in-node-j)does.

2019-12-05 21:48 UTC, jlee273 commented
Hi Nick,

Where should I find the video you sent to the class?

Jieun Lee

> On Dec 5, 2019, at 9:43 AM, Nick Briz <notifications@github.com> wrote:
> 
> @jlee273 <https://github.com/jlee273> did u watch the video i sent to the class via email? i explain more or less what u should do in that video. for app.post('/api/image-upload') u should use the 'multer' library (explained in the video i made) && for app.get('/api/images') u should use the fs module to read all the filenames in the folder && send them back as json. in the video i explain how to send json back, but i don't explain how to read all the file names in a folder, but this post  <https://stackoverflow.com/questions/2727167/how-do-you-get-a-list-of-the-names-of-all-files-present-in-a-directory-in-node-j>does.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/net-art-and-cultures/data-bodies/pull/40?email_source=notifications&email_token=ANCPPLDS537O7VYEWMCFAHTQXEOTVA5CNFSM4JVVG252YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGBEOVQ#issuecomment-562186070>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ANCPPLHXEJ5Y27E6I7VYTG3QXEOTVANCNFSM4JVVG25Q>.
>

2019-12-05 23:17 UTC, nbriz commented
in ur SAIC email, i emailed everyone a few days ago, the title of the email was: "Net Art Final: Questions + Answers" ur email is jlee273 @ saic.edu right?

2019-12-06 05:04 UTC, jlee273 commented
I got it. Thanks.

> On Dec 5, 2019, at 5:17 PM, Nick Briz <notifications@github.com> wrote:
> 
> in ur SAIC email, i emailed everyone a few days ago, the title of the email was: "Net Art Final: Questions + Answers" ur email is jlee273 @ saic.edu right?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/net-art-and-cultures/data-bodies/pull/40?email_source=notifications&email_token=ANCPPLEFFJBWRFZPRXQCBUDQXGDX3A5CNFSM4JVVG252YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGCPJXQ#issuecomment-562361566>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ANCPPLH2BD2L7NZ5TAHIOFTQXGDX3ANCNFSM4JVVG25Q>.
>

2019-12-06 18:56 UTC, jlee273 reviewed
change server.js

2019-12-06 18:58 UTC, jlee273 commented
I cannot hear the sound of the video you sent us.

2019-12-06 23:26 UTC, nbriz commented
@jlee273 it looks like u copied exactly (word for word) what i did in the tutorial. but like i mention in the tutorial, the project i'm working on is an instagram clone, ur project is different from the one i did in the tutorial. the purpose of the video tutorial is not so u can copy exactly, but so u can see the different sorts of pieces (in context) that u'll need to implement, but u'll have to change the details so that it relates to ur specific project.

i my previous comment i said:

> did u watch the video i sent to the class via email? i explain more or less what u should do in that video. for `app.post('/api/image-upload')` u should use the 'multer' library (explained in the video i made) && for `app.get('/api/images')` u should use the `fs` module to read all the filenames in the folder && send them back as json. in the video i explain how to send json back, but i don't explain how to read all the file names in a folder, but [this post ](https://stackoverflow.com/questions/2727167/how-do-you-get-a-list-of-the-names-of-all-files-present-in-a-directory-in-node-j)does.

2019-12-09 04:00 UTC, nbriz requested changes
Jieun, when i tried to run ur code i got a lot of bugs. this makes me think that when u followed my tutorial u never bothered to test ur code along the way. everytime u make a change to ur code u should test it, otherwise there's no way to know if it's actually working. this is why in the video i sent i'm constantly relaunching the server when i make changes to test it. this is also why i made those jsfiddle links for u, so u could use those to test the API. but the amount of bugs in ur code makes me think u never tested it.

i've left lots of comments relating to all the bugs i found, please fix these. also i need u to delete the `.DS_Store` file as well as the one in the server folder, `server/.DS_Store`

2019-12-09 04:00 UTC, nbriz commented on server/app.js
> +const app = express();
i'm not sure why this file `app.js` is here, was this a mistake? if so delete it && commit + push the update (so that it also gets deleted from this pull request)

2019-12-09 04:00 UTC, nbriz commented on server/server.js
> +const upload = multer({ dest; 'www/uploads/' })
did u try running ur server? b/c when i tried to run it i got this error: 
```
const upload = multer({ dest; 'www/uploads/' })
                            ^

SyntaxError: Unexpected token ;

```
what that error is saying is that i found a `;` where it was not expecting one, that's b/c it should be a `:`

2019-12-09 04:00 UTC, nbriz commented on server/server.js
> +app.post('/api/image-upload', uplpad.single('image'), (req, res) => {
after that, when i tried to run the server i got another error here, saying that `uplpad is not defined`, b/c there is no variable called 'uplpad' it's called 'upload'

2019-12-09 04:00 UTC, nbriz commented on server/server.js
> +const staticFiles = express.static('${__dirname}www')
i don't know why u changed this part to:
```js
 const staticFiles = express.static('${__dirname}www')
```
with single quotes instead of the tick marks. u also got rid of the `/` before `www` for some reason. it should look like it did before like this:
```js
 const staticFiles = express.static(`${__dirname}/www`)
```
b/c anytime u want to pass variables into strings like this `${variable}` u need to use the tick marks not the quote marks

2019-12-09 04:00 UTC, nbriz commented on server/server.js
> +  res.header('Acccess-Control-Allow-Origin', '*')
u have an extra 'c' in 'Access', it should say `Access` not `Acccess`

2019-12-09 04:00 UTC, nbriz commented on server/server.js
> +  res.header('Access-Control-Allow-Methods', 'GET, Post, PUT, DELETE, OPTIONS')
`Post` needs to be in uppercase like this `POST`

2019-12-09 16:51 UTC, nbriz reviewed
I left u a couple of comments (which i also mentioned before) which still need to be fixed. Also, u still have a `.DS_Store` in ur repo: https://github.com/jlee273/data-bodies make sure u delete that file (otherwise GitHub won't let me merge ur code)

2019-12-09 16:51 UTC, nbriz commented on server/server.js
> +const staticFiles = express.static('${__dirname}/www')
when we pass varialbes (like `__dirname` or `port`) into strings like this `${__dirname}` we need to create that string with tick marks, not quotes. u have a string with quotes like this:
```js
'${__dirname}/www'
```
but they should be tick marks like this:
```js
`${__dirname}/www`
```

2019-12-09 16:51 UTC, nbriz commented on server/server.js
> +  console.log('Server running at http://localhost:${port}, CTRL + to shutdown')
here we have the same issue as above, these should be tick marks not strings (also it should say "CTRL + C to shutdown" not "CTRL + to shutdown"), so u are logging this:
```js
'Server running at http://localhost:${port}, CTRL + to shutdown'
```
but u should be logging this
```js
`Server running at http://localhost:${port}, CTRL + C to shutdown`
```

2019-12-09 17:02 UTC, jlee273 commented
I deleted .DS_Store in my repo and fixed others.

2019-12-09 18:15 UTC, merged